### ISSUE TITLE
Baseorder (clipit-order) not working on mac

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#48] opened 2016-03-01 20:10 UTC
So I'm trying to get Ran's baseorder working on my mac and am running into an error whenever I try to do anything with it.

The error is usually formatted like so:

> Uncaught TypeError: Cannot read property of 'length' of undefined

Any ideas what might be causing this? It seems like it has to do with the history variable, maybe something with the serialization?

**Comment by cleebp** [comment] 2016-03-01 20:10
Were you able to get it working on your machine Arjun?

**Comment by reachspirit** [comment] 2016-03-01 21:01
How do you install the package. I lost all my manually installed packages. I'll test it if I can get them installed again.

**Comment by cleebp** [comment] 2016-03-01 21:03
I go to the directory in terminal where the package is located, type "apm install" then "apm link".

**Comment by reachspirit** [comment] 2016-03-01 21:07
There's something wrong with the program, I'll fix it in a while. Sorry about that.

**Comment by reachspirit** [comment] 2016-03-02 02:15
I found the reason for this bug. All you need to do is go to baseorder.coffee and comment the 'if' statement within 'active'. Reload the program and then restore the code. The bug should be fixed this time. I guess the problem is that I pushed some irregular items to history. So clear history would work.

**Comment by arjunmadan** [comment] 2016-03-02 03:54
Can you fix that submit a pull request? (Or just commit to master directly, but be careful. xD)

**Comment by arjunmadan** [comment] 2016-03-02 19:18
Fixed.

**Closed as completed by arjunmadan** 2016-03-02 19:18 UTC
Labels: bug, Mar 1, in testing
