### ISSUE TITLE
Problem with clipit-panel

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#70] opened 2016-03-28 01:52 UTC
Clipit-panel doesn't support copy and paste from webpage. We have to right click the mouse to copy and paste the item. Also, it reported an error after using mouse.

![img_20160327_210709r](https://cloud.githubusercontent.com/assets/16613192/14069316/1d644d62-f466-11e5-8751-d5639264f138.jpg)

**Comment by arjunmadan** [comment] 2016-03-28 01:55
That error is actually with the baseorder package. Clipit-panel worked fine for me.

**Comment by arjunmadan** [comment] 2016-03-28 01:56
Also, I don't think any of them work with copying from the browser. With the panel version, I noticed it added it to the panel on pasting.

**Comment by reachspirit** [comment] 2016-03-28 01:58
You can see from the picture that it indeed is a problem with clipit-panel.

**Comment by arjunmadan** [comment] 2016-03-28 01:58
The picture says the error was thrown by the baseorder package.

**Comment by reachspirit** [comment] 2016-03-28 02:03
But I disabled the baseorder package while testing the panel. And baseorder does support copy and paste from webpage.

**Comment by arjunmadan** [comment] 2016-03-28 02:04
Not sure what the problem is then. What I meant by "not work" was that it doesn't add anything to the clipboard while copying from an external source. It gets added only when the text is pasted.

**Comment by reachspirit** [comment] 2016-03-28 02:10
It should work when history is not empty, but doesn't work if history is empty. I don't know the reason either.

**Comment by effat** [comment] 2016-03-28 03:27
Thanks for pointing out. I've fixed it.

**Comment by effat** [comment] 2016-03-28 03:29
But there is a bug in the base version...i.e. if you copy and paste something in clipboard, and then clear the history by yourself (without closing the program), then if you again try to copy and paste from external source, it does not work :/

**Comment by cleebp** [comment] 2016-03-28 03:46
Well it looks like we are certainly getting data and feedback - also for tomorrows meeting i just remembered that I have office hours from 12-1 so I wont be able to get there till 1 (ill try to leave early).

**Comment by arjunmadan** [comment] 2016-03-28 03:48
I managed to get all four done! :D

12:30 to 2. Don’t think we’ll have that much to discuss anyway (I hope).

-- 
Arjun

On March 27, 2016 at 11:46:45 PM, Brian Clee (notifications@github.com) wrote:

Well it looks like we are certainly getting data and feedback - also for tomorrows meeting i just remembered that I have office hours from 12-1 so I wont be able to get there till 1 (ill try to leave early).

**Closed as completed** 2016-03-28 17:53 UTC
